#include <iostream>
#include <random>
#include <cstdlib>
#include <ctime>

#include "cxxopts.hpp"

// default_values.h will get autogenerated through build.sh
#include "default_values.h"


int main(int argc, char *argv[]){

  cxxopts::Options options("DGaussGen", "Gaussian noise generator to json format");

  options.add_options()
    ("u,mean", "Mean value", cxxopts::value<double>()->default_value(MEAN_DEFAULT))
    ("d,std", "Standard deviation", cxxopts::value<double>()->default_value(STD_DEFAULT))
    ("s,seed", "Start seed, default means current time will be used", cxxopts::value<long>()->default_value("-1"))
    ("l,limit", "Number of samples generated", cxxopts::value<long>()->default_value(LIMIT_DEFAULT))
    ("h,help", "Display this help message")
    ;

  auto result = options.parse(argc, argv);
  if(result["help"].as<bool>()){
    std::cout << options.help();
    return 0;
  }

  double mu = result["mean"].as<double>();
  double stdev = result["std"].as<double>();
  long seed = result["seed"].as<long>();
  if(seed == -1){
    seed = std::time(nullptr);
  }
  long limit = result["limit"].as<long>();
  
  std::default_random_engine gen(seed);

  std::normal_distribution<double> dist(mu,stdev);  

  std::cout << "[";
  int i = 0;
  while(true){
    std::cout << dist(gen);
    if(++i < limit){
      std::cout << ",";
    } else{
      break;
    }
  }
  std::cout << "]\n";      
}
